Desktop/TestApplication8/TestApplication/TestApplication7/Models/RateModel.cs
using System.ComponentModel.DataAnnotations;

namespace TestApplication7.Models
{
    public class RatingModel
    {
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "length cannot be zero")]
        public int Length { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "width cannot be zero")]
        public int Width { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "height cannot be zero")]
        public int Height { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "weight cannot be zero")]
        public int Weight { get; set; }
        [Required]
        [RegularExpression(@"^((?!.*L4N 3P8.*).)*$", ErrorMessage = "You cannot rate shop this postal code")]
        public string PostalCode { get; set; }




    }
}

Desktop/TestApplication8/TestApplication/TestApplication7/Models/ViewRatingModel.cs
namespace TestApplication7.Models
{
    public class ViewRatingModel
    {
        public RatingModel Ratemodel { get; set; }
        public decimal EstimatedCost { get; set; }

        public string Error { get; set; }
        public string Message { get; set; }

    }
}

Desktop/TestApplication8/TestApplication/TestApplication7/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TestApplication7.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Desktop/TestApplication8/TestApplication/TestApplication7/Controllers/RateController.cs
using System.Web.Mvc;
using TestApplication7.Models;
using TestApplication7.Services.Ics;

namespace TestApplication7.Controllers
{
    public class RateController : Controller
    {
        // GET: Rate
        public ActionResult Index()
        {
            return View(new ViewRatingModel());
        }

        [HttpPost]
        public ActionResult Index(ViewRatingModel viewModel)
        {
            ViewRatingModel rate = new ViewRatingModel();
            {

                var api = new IcsServices();
                decimal result = api.GetEstimatedCharges(viewModel.Ratemodel.Weight, viewModel.Ratemodel.Width, viewModel.Ratemodel.Length, viewModel.Ratemodel.Height, viewModel.Ratemodel.PostalCode);

                rate.EstimatedCost = result;
                rate.Ratemodel = viewModel.Ratemodel;

                if (result == 0)
                    rate.Error = "Something went wrong with this request";

                if (result <= 10)
                    rate.Message = "This is a very inexpensive rate";

                if (result >= 10)
                    rate.Message = "This is an expensive rate";

            }
            return View("Post", rate);

        }
    }

}

Desktop/TestApplication8/TestApplication/TestApplication7/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Desktop/TestApplication8/TestApplication/TestApplication7/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Desktop/TestApplication8/TestApplication/TestApplication7/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Test Applications</h1>
    <p class="lead">Please rewrite the rating part of this applications.</p>
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Rate Shop ICS</h2>
        <p>
            Use this option to Rate Shop a Test Shipment
        </p>
        <p>@Html.ActionLink("Rate Shop", "Index", "Rate")</p>
    </div>
</div>

Desktop/TestApplication8/TestApplication/TestApplication7/Views/Rate/Index.cshtml
@model TestApplication7.Models.ViewRatingModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ratingmodel</h4>

        <p>
            To rate shop a shipment, enter dimensions in Inches (for example 6 8 and 10), enter a weight in Lbs, 5 (for example). For postal code use upper case M9W7J2 as an example
        </p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ratemodel.Length, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ratemodel.Length, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ratemodel.Length, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ratemodel.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ratemodel.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ratemodel.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ratemodel.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ratemodel.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ratemodel.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ratemodel.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ratemodel.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ratemodel.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ratemodel.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ratemodel.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ratemodel.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Get Rate" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Desktop/TestApplication8/TestApplication/TestApplication7/Views/Rate/Post.cshtml
@model TestApplication7.Models.ViewRatingModel
@{
    ViewBag.Title = "Post";
}


@{
    Layout = null;
}

<h2>Post</h2>
<p>
    Here is the rating response for ICS Next Day for a
<p>Error: @Model.Error</p>
<p>Message: @Model.Message</p>
@Model.Ratemodel.Length
@Model.Ratemodel.Height
@Model.Ratemodel.Width

<br />
    Weighing : @Model.Ratemodel.Weight Lbs
    <br />
    To Postal Code: @Model.Ratemodel.PostalCode
    </p>
    <p>Result for rating is @Model.EstimatedCost</p>

    <p>@Html.ActionLink("Rate again?", "Index", "Home")</p>

Desktop/TestApplication8/TestApplication/TestApplication7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>